import type { Movie, Tag, WatchRecord } from "@/lib/types";

export const mockTags: Tag[] = [
  { id: "t1", label: "인생영화" },
  { id: "t2", label: "눈물버튼" },
  { id: "t3", label: "OST 최고" },
  { id: "t4", label: "재관람각" },
  { id: "t5", label: "몰입감 甲" },
  { id: "t6", label: "결말 충격" },
  { id: "t7", label: "힐링" },
  { id: "t8", label: "취향저격" },
];

export const mockMovies: Movie[] = [
  { id: "m1", title: "파일럿", posterUrl: null },
  { id: "m2", title: "서울의 봄", posterUrl: null },
  { id: "m3", title: "인사이드 아웃 2", posterUrl: null },
  { id: "m4", title: "웡카", posterUrl: null },
  { id: "m5", title: "듄: 파트 2", posterUrl: null },
  { id: "m6", title: "패스트 라이브즈", posterUrl: null },
];

export const mockWatchRecords: WatchRecord[] = [
  {
    id: "r1",
    movieId: "m1",
    status: "watched",
    watchedFrom: "2024.05.02",
    companions: ["민지"],
    locations: ["CGV 강남"],
    tags: [mockTags[0], mockTags[6]],
    note: "코미디인데 은근 뭉클해서 놀랐다. 상영관 분위기도 좋았음.",
    rewatchIntent: "yes",
  },
  {
    id: "r2",
    movieId: "m2",
    status: "dropped",
    watchedFrom: "2024.01.20",
    companions: [],
    locations: ["집"],
    tags: [mockTags[4], mockTags[5]],
    note: "보는 내내 숨 막혔다. 배우들 연기 최고.",
    rewatchIntent: "no",
  },
  {
    id: "r3",
    movieId: "m3",
    status: "watched",
    watchedFrom: "2024.06.14",
    companions: ["재현", "소율"],
    locations: ["롯데시네마 월드타워"],
    tags: [mockTags[1], mockTags[6]],
    rewatchIntent: "yes",
  },
  {
    id: "r4",
    movieId: "m3",
    status: "watched",
    watchedFrom: "2024.07.03",
    companions: [],
    locations: ["집"],
    tags: [mockTags[3]],
    note: "두 번째 볼 때 더 웃김. 불안이 편집증적으로 굴 때마다 빵 터짐.",
    rewatchIntent: "yes",
  },
  {
    id: "r5",
    movieId: "m4",
    status: "watched",
    watchedFrom: "2024.02.11",
    companions: ["가족"],
    locations: ["메가박스 코엑스"],
    tags: [mockTags[2], mockTags[6]],
    note: "티모시 샬라메 노래 실력 미쳤다.",
    rewatchIntent: "yes",
  },
  {
    id: "r6",
    movieId: "m5",
    status: "rewatched",
    watchedFrom: "2024.03.15",
    companions: ["민지", "재현"],
    locations: ["CGV 용산아이파크몰"],
    tags: [mockTags[4], mockTags[0]],
    note: "아이맥스로 봐서 그런지 스케일이 압도적이었다.",
    rewatchIntent: "yes",
  },
  {
    id: "r7",
    movieId: "m6",
    status: "watched",
    watchedFrom: "2024.04.27",
    companions: [],
    locations: ["왓챠"],
    tags: [mockTags[1], mockTags[7]],
    note: "잔잔하게 마음을 후벼판다.",
    rewatchIntent: "no",
  },
];
